receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  # Change from localhost to 0.0.0.0

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
