info:
  contact:
    email: tech@corvus-tech.com
    name: API Support
    url: https://corvus-tech.com/contact-us
  description: This API documents exposes all the available API endpoints for USSD
    Wrapper service
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://corvus-tech.com/terms
  title: USSD Wrapper Service API
  version: "3.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: api-key
    type: apiKey
swagger: "2.0"
